name = "НИИ ГУМАНИЗМ"
author = "Llirkit, QudReR"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42705ffd65e3e60dd12c2c296fa531e81b34ec0bf7a8c62605631017944395d4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
