name = "НИИ ГУМАНИЗМ"
author = "Llirkit, QudReR"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9641a5bde7e9241cf9e208af572d88702e4191ff81dc6cae269c1c64007ccf7d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
