name = "НИИ ГУМАНИЗМ"
author = "Llirkit, QudReR"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ea75560bd2660e86edf4ef8d38397328f1de088f58d943f7c7d53296012973f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
